//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hdata : DbContext
    {
        public hdata()
            : base("name=hdata")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAppointment> tblAppointment { get; set; }
        public virtual DbSet<tblAppointmentStatus> tblAppointmentStatus { get; set; }
        public virtual DbSet<tblDepartment> tblDepartment { get; set; }
        public virtual DbSet<tblDoctor> tblDoctor { get; set; }
        public virtual DbSet<tblPatient> tblPatient { get; set; }
        public virtual DbSet<tblVisitType> tblVisitType { get; set; }
        public virtual DbSet<tblVisitPerDoc> tblVisitPerDoc { get; set; }
        public virtual DbSet<viewVisitPerDoc> viewVisitPerDoc { get; set; }
        public virtual DbSet<viewAppointment> viewAppointment { get; set; }
        public virtual DbSet<tblCommon> tblCommon { get; set; }
        public virtual DbSet<viewCommon> viewCommon { get; set; }
        public virtual DbSet<tblType> tblType { get; set; }
        public virtual DbSet<tblLanguage> tblLanguage { get; set; }
        public virtual DbSet<viewChangeLng> viewChangeLng { get; set; }
    }
}
