//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int pkID { get; set; }
        public int fkDocID { get; set; }
        public Nullable<int> fkPID { get; set; }
        public Nullable<int> fkVTID { get; set; }
        public System.DateTime sDate { get; set; }
        public Nullable<System.DateTime> eDate { get; set; }
        public Nullable<int> fkAppointmentStatus { get; set; }
    
        public virtual tblAppointmentStatus tblAppointmentStatus { get; set; }
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblPatient tblPatient { get; set; }
        public virtual tblVisitType tblVisitType { get; set; }
    }
}
