//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewChangeLng
    {
        public int pkID { get; set; }
        public string name { get; set; }
        public string itmContent { get; set; }
        public string description { get; set; }
        public int fkTypID { get; set; }
        public int fkLngID { get; set; }
        public string lngName { get; set; }
        public string language { get; set; }
    }
}
