//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAppointment
    {
        public int pkID { get; set; }
        public int fkDocID { get; set; }
        public System.DateTime sDate { get; set; }
        public Nullable<int> fkPID { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string fSDate { get; set; }
        public string time { get; set; }
        public string pName { get; set; }
        public string pFamily { get; set; }
        public string pMobile { get; set; }
        public string appointmentStatus { get; set; }
        public Nullable<int> fkAppointmentStatus { get; set; }
        public string pNC { get; set; }
        public string type { get; set; }
        public Nullable<int> fkVTID { get; set; }
        public Nullable<System.DateTime> eDate { get; set; }
    }
}
